// Mocks generated by Mockito 5.4.4 from annotations
// in vital_step/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:flutter/material.dart' as _i12;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:get_storage/get_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:stacked_services/stacked_services.dart' as _i10;
import 'package:timezone/timezone.dart' as _i8;
import 'package:vital_step/Model/accounts.dart' as _i22;
import 'package:vital_step/Model/Assessment.dart' as _i20;
import 'package:vital_step/Model/Comment.dart' as _i21;
import 'package:vital_step/Model/connection_status.dart' as _i6;
import 'package:vital_step/Model/Device.dart' as _i18;
import 'package:vital_step/Model/device_selection_state.dart' as _i5;
import 'package:vital_step/Model/profile.dart' as _i3;
import 'package:vital_step/Model/SignUpInfo.dart' as _i16;
import 'package:vital_step/Model/spcialist_profile.dart' as _i9;
import 'package:vital_step/Model/test.dart' as _i4;
import 'package:vital_step/services/accounts_service.dart' as _i17;
import 'package:vital_step/services/api_calls_service.dart' as _i19;
import 'package:vital_step/services/device_selection_service.dart' as _i23;
import 'package:vital_step/services/login_service.dart' as _i15;
import 'package:vital_step/services/notifications_service.dart' as _i24;
import 'package:vital_step/services/specialist_service.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetStorage_0 extends _i1.SmartFake implements _i2.GetStorage {
  _FakeGetStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTest_2 extends _i1.SmartFake implements _i4.Test {
  _FakeTest_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceSelectionState_3 extends _i1.SmartFake
    implements _i5.DeviceSelectionState {
  _FakeDeviceSelectionState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectionStatus_4 extends _i1.SmartFake
    implements _i6.ConnectionStatus {
  _FakeConnectionStatus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterLocalNotificationsPlugin_5 extends _i1.SmartFake
    implements _i7.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTZDateTime_6 extends _i1.SmartFake implements _i8.TZDateTime {
  _FakeTZDateTime_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileSpecialist_7 extends _i1.SmartFake
    implements _i9.ProfileSpecialist {
  _FakeProfileSpecialist_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i10.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i12.GlobalKey<_i12.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i12.GlobalKey<_i12.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i10.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?>? navigateWithTransition<T>(
    _i12.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i12.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i10.Transition? transitionClass,
    _i10.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? replaceWithTransition<T>(
    _i12.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i12.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i10.Transition? transitionClass,
    _i10.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i12.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i12.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? navigateToView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i12.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i10.Transition? transition,
    _i10.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i12.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearStackAndShowView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? clearTillFirstAndShowView<T>(
    _i12.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);

  @override
  _i13.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i12.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i13.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i10.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i10.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i10.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i13.Future<_i10.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.SheetResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.SheetResponse<dynamic>?>);

  @override
  _i13.Future<_i10.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i14.Color? barrierColor = const _i14.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i13.Future<_i10.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i13.Future<_i10.SheetResponse<T>?>.value(),
      ) as _i13.Future<_i10.SheetResponse<T>?>);

  @override
  void completeSheet(_i10.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i10.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i10.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i12.Widget Function(
      _i12.BuildContext,
      _i10.DialogRequest<dynamic>,
      dynamic Function(_i10.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i10.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i14.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i14.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i12.RouteSettings? routeSettings,
    _i12.GlobalKey<_i12.NavigatorState>? navigatorKey,
    _i10.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<dynamic>?>);

  @override
  _i13.Future<_i10.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i14.Color? barrierColor = const _i14.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    _i12.RouteSettings? routeSettings,
    _i12.GlobalKey<_i12.NavigatorState>? navigatorKey,
    _i12.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i13.Future<_i10.DialogResponse<T>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<T>?>);

  @override
  _i13.Future<_i10.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i14.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i14.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i12.RouteSettings? routeSettings,
    _i10.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i13.Future<_i10.DialogResponse<dynamic>?>.value(),
      ) as _i13.Future<_i10.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i10.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i15.LoginService {
  @override
  _i2.GetStorage get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.GetStorage);

  @override
  _i13.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<void> signIn(
    String? email,
    String? password,
    String? selectedUserType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
            selectedUserType,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> signUp(_i16.SignUpInfo? signUpInfo) => (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signUpInfo],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<String?> getCookie({
    required String? userId,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCookie,
          [],
          {
            #userId: userId,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  dynamic updateProfile(_i16.SignUpInfo? signUpInfo) => super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [signUpInfo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<String?> getUserType() => (super.noSuchMethod(
        Invocation.method(
          #getUserType,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);
}

/// A class which mocks [AccountsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountsService extends _i1.Mock implements _i17.AccountsService {
  @override
  _i2.GetStorage get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.GetStorage);

  @override
  _i13.Future<_i3.Profile> getAccountDetails({int? patientUserId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountDetails,
          [],
          {#patientUserId: patientUserId},
        ),
        returnValue: _i13.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #getAccountDetails,
            [],
            {#patientUserId: patientUserId},
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #getAccountDetails,
            [],
            {#patientUserId: patientUserId},
          ),
        )),
      ) as _i13.Future<_i3.Profile>);

  @override
  _i13.Future<List<_i18.Device>> getDevices() => (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
        ),
        returnValue: _i13.Future<List<_i18.Device>>.value(<_i18.Device>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i18.Device>>.value(<_i18.Device>[]),
      ) as _i13.Future<List<_i18.Device>>);

  @override
  _i13.Future<void> addDevice({
    required String? deviceCode,
    required String? deviceName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDevice,
          [],
          {
            #deviceCode: deviceCode,
            #deviceName: deviceName,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> killApp() => (super.noSuchMethod(
        Invocation.method(
          #killApp,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [ApiCallsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiCallsService extends _i1.Mock implements _i19.ApiCallsService {
  @override
  _i2.GetStorage get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.GetStorage);

  @override
  _i13.Future<List<_i20.Assessment>> getAllUserAssessments(
          {int? patientUserId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUserAssessments,
          [],
          {#patientUserId: patientUserId},
        ),
        returnValue:
            _i13.Future<List<_i20.Assessment>>.value(<_i20.Assessment>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i20.Assessment>>.value(<_i20.Assessment>[]),
      ) as _i13.Future<List<_i20.Assessment>>);

  @override
  _i13.Future<List<_i4.Test>> getAllUserTests() => (super.noSuchMethod(
        Invocation.method(
          #getAllUserTests,
          [],
        ),
        returnValue: _i13.Future<List<_i4.Test>>.value(<_i4.Test>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i4.Test>>.value(<_i4.Test>[]),
      ) as _i13.Future<List<_i4.Test>>);

  @override
  _i13.Future<_i4.Test> getLastTest() => (super.noSuchMethod(
        Invocation.method(
          #getLastTest,
          [],
        ),
        returnValue: _i13.Future<_i4.Test>.value(_FakeTest_2(
          this,
          Invocation.method(
            #getLastTest,
            [],
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i4.Test>.value(_FakeTest_2(
          this,
          Invocation.method(
            #getLastTest,
            [],
          ),
        )),
      ) as _i13.Future<_i4.Test>);

  @override
  _i13.Future<List<_i4.Test>> getAllAssessmentTests(
          {required int? assessmentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAssessmentTests,
          [],
          {#assessmentId: assessmentId},
        ),
        returnValue: _i13.Future<List<_i4.Test>>.value(<_i4.Test>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i4.Test>>.value(<_i4.Test>[]),
      ) as _i13.Future<List<_i4.Test>>);

  @override
  _i13.Future<List<String>> getAllPossibleDevices() => (super.noSuchMethod(
        Invocation.method(
          #getAllPossibleDevices,
          [],
        ),
        returnValue: _i13.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i13.Future<List<String>>.value(<String>[]),
      ) as _i13.Future<List<String>>);

  @override
  _i13.Future<List<String>> getAssessmentQueue(
          {required String? assessmentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssessmentQueue,
          [],
          {#assessmentId: assessmentId},
        ),
        returnValue: _i13.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i13.Future<List<String>>.value(<String>[]),
      ) as _i13.Future<List<String>>);

  @override
  dynamic createTestQueue({
    required _i20.Assessment? assessment,
    required String? hand,
    required String? deviceId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #createTestQueue,
          [],
          {
            #assessment: assessment,
            #hand: hand,
            #deviceId: deviceId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> deleteTest({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #deleteTest,
          [],
          {#id: id},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> sendResetPasswordEmail({
    required String? email,
    required String? userType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendResetPasswordEmail,
          [],
          {
            #email: email,
            #userType: userType,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<List<_i21.Comment>> getComments({required int? assessmentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [],
          {#assessmentId: assessmentId},
        ),
        returnValue: _i13.Future<List<_i21.Comment>>.value(<_i21.Comment>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i21.Comment>>.value(<_i21.Comment>[]),
      ) as _i13.Future<List<_i21.Comment>>);

  @override
  _i13.Future<List<_i22.Accounts>> getSpecialists() => (super.noSuchMethod(
        Invocation.method(
          #getSpecialists,
          [],
        ),
        returnValue: _i13.Future<List<_i22.Accounts>>.value(<_i22.Accounts>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i22.Accounts>>.value(<_i22.Accounts>[]),
      ) as _i13.Future<List<_i22.Accounts>>);

  @override
  _i13.Future<List<Map<String, int>>> getUserQueue() => (super.noSuchMethod(
        Invocation.method(
          #getUserQueue,
          [],
        ),
        returnValue:
            _i13.Future<List<Map<String, int>>>.value(<Map<String, int>>[]),
        returnValueForMissingStub:
            _i13.Future<List<Map<String, int>>>.value(<Map<String, int>>[]),
      ) as _i13.Future<List<Map<String, int>>>);

  @override
  _i13.Future<void> cancelAssessment({required int? queueId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAssessment,
          [],
          {#queueId: queueId},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<int> getQueueId(_i20.Assessment? assessment) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQueueId,
          [assessment],
        ),
        returnValue: _i13.Future<int>.value(0),
        returnValueForMissingStub: _i13.Future<int>.value(0),
      ) as _i13.Future<int>);
}

/// A class which mocks [DeviceSelectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceSelectionService extends _i1.Mock
    implements _i23.DeviceSelectionService {
  @override
  _i13.Stream<_i18.Device?> get selectedDeviceStream => (super.noSuchMethod(
        Invocation.getter(#selectedDeviceStream),
        returnValue: _i13.Stream<_i18.Device?>.empty(),
        returnValueForMissingStub: _i13.Stream<_i18.Device?>.empty(),
      ) as _i13.Stream<_i18.Device?>);

  @override
  _i13.Stream<_i5.DeviceSelectionState> get selectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#selectionStateStream),
        returnValue: _i13.Stream<_i5.DeviceSelectionState>.empty(),
        returnValueForMissingStub:
            _i13.Stream<_i5.DeviceSelectionState>.empty(),
      ) as _i13.Stream<_i5.DeviceSelectionState>);

  @override
  _i5.DeviceSelectionState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _FakeDeviceSelectionState_3(
          this,
          Invocation.getter(#currentState),
        ),
        returnValueForMissingStub: _FakeDeviceSelectionState_3(
          this,
          Invocation.getter(#currentState),
        ),
      ) as _i5.DeviceSelectionState);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i13.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> selectDevice(_i18.Device? device) => (super.noSuchMethod(
        Invocation.method(
          #selectDevice,
          [device],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> clearSelection() => (super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> updateConnectionStatus(
    _i18.Device? device,
    _i6.ConnectionStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConnectionStatus,
          [
            device,
            status,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i6.ConnectionStatus getConnectionStatus(_i18.Device? device) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [device],
        ),
        returnValue: _FakeConnectionStatus_4(
          this,
          Invocation.method(
            #getConnectionStatus,
            [device],
          ),
        ),
        returnValueForMissingStub: _FakeConnectionStatus_4(
          this,
          Invocation.method(
            #getConnectionStatus,
            [device],
          ),
        ),
      ) as _i6.ConnectionStatus);

  @override
  _i13.Future<_i18.Device?> getPersistedSelection() => (super.noSuchMethod(
        Invocation.method(
          #getPersistedSelection,
          [],
        ),
        returnValue: _i13.Future<_i18.Device?>.value(),
        returnValueForMissingStub: _i13.Future<_i18.Device?>.value(),
      ) as _i13.Future<_i18.Device?>);

  @override
  bool hasPersistedSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasPersistedSelection,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setLoading(bool? isLoading) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [isLoading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsService extends _i1.Mock
    implements _i24.NotificationsService {
  @override
  _i7.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#flutterLocalNotificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_5(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
        returnValueForMissingStub: _FakeFlutterLocalNotificationsPlugin_5(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
      ) as _i7.FlutterLocalNotificationsPlugin);

  @override
  _i13.Future<bool> checkNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkNotificationPermission,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
        returnValueForMissingStub: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> requestNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationPermission,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> scheduleNotifications({
    required _i20.Assessment? assessment,
    required DateTime? startDateTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotifications,
          [],
          {
            #assessment: assessment,
            #startDateTime: startDateTime,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i8.TZDateTime scheduleDate({
    required String? schedule,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDate,
          [],
          {
            #schedule: schedule,
            #startDate: startDate,
          },
        ),
        returnValue: _FakeTZDateTime_6(
          this,
          Invocation.method(
            #scheduleDate,
            [],
            {
              #schedule: schedule,
              #startDate: startDate,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTZDateTime_6(
          this,
          Invocation.method(
            #scheduleDate,
            [],
            {
              #schedule: schedule,
              #startDate: startDate,
            },
          ),
        ),
      ) as _i8.TZDateTime);

  @override
  _i13.Future<void> clearAllFutureNotifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllFutureNotifications,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> sendNotificationInSomeTime() => (super.noSuchMethod(
        Invocation.method(
          #sendNotificationInSomeTime,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> handleNotification() => (super.noSuchMethod(
        Invocation.method(
          #handleNotification,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [SpecialistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpecialistService extends _i1.Mock implements _i25.SpecialistService {
  @override
  _i2.GetStorage get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeGetStorage_0(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.GetStorage);

  @override
  _i13.Future<_i9.ProfileSpecialist> getSpecialistProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecialistProfile,
          [],
        ),
        returnValue:
            _i13.Future<_i9.ProfileSpecialist>.value(_FakeProfileSpecialist_7(
          this,
          Invocation.method(
            #getSpecialistProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i9.ProfileSpecialist>.value(_FakeProfileSpecialist_7(
          this,
          Invocation.method(
            #getSpecialistProfile,
            [],
          ),
        )),
      ) as _i13.Future<_i9.ProfileSpecialist>);

  @override
  _i13.Future<List<_i22.Accounts>> getAccounts() => (super.noSuchMethod(
        Invocation.method(
          #getAccounts,
          [],
        ),
        returnValue: _i13.Future<List<_i22.Accounts>>.value(<_i22.Accounts>[]),
        returnValueForMissingStub:
            _i13.Future<List<_i22.Accounts>>.value(<_i22.Accounts>[]),
      ) as _i13.Future<List<_i22.Accounts>>);

  @override
  _i13.Future<String?> getSpecialistName() => (super.noSuchMethod(
        Invocation.method(
          #getSpecialistName,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
        returnValueForMissingStub: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<void> addPatient({
    required String? patientEmail,
    required String? patientAccessCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPatient,
          [],
          {
            #patientEmail: patientEmail,
            #patientAccessCode: patientAccessCode,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteAccountAccess({int? id}) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccountAccess,
          [],
          {#id: id},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> createAssessment(
    String? posture,
    String? assessmentType,
    String? patientId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAssessment,
          [
            posture,
            assessmentType,
            patientId,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  dynamic deleteAssessment({required String? assessmentId}) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteAssessment,
          [],
          {#assessmentId: assessmentId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> addComment({
    required String? comment,
    required int? assessmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [],
          {
            #comment: comment,
            #assessmentId: assessmentId,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  dynamic deleteRemark({required int? remarkId}) => super.noSuchMethod(
        Invocation.method(
          #deleteRemark,
          [],
          {#remarkId: remarkId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic updateProfile(_i9.ProfileSpecialist? signUpInfo) =>
      super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [signUpInfo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> signUp(_i9.ProfileSpecialist? signUpInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signUpInfo],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}
